sudo: false
language: go
go:
- 1.8.1
before_install:
- go get github.com/Masterminds/glide
- if [ ! -d $CODE_DIRECTORY ]; then mkdir -p $HOME/gopath/src/github.com/Nike-Inc; ln -s $TRAVIS_BUILD_DIR $CODE_DIRECTORY; fi # CI for forks
env:
  global:
  - GLIDE_HOME="${HOME}/.glide"
  - CODE_DIRECTORY=$HOME/gopath/src/github.com/Nike-Inc/cerberus-go-client
install:
- cd $CODE_DIRECTORY # change dir into source
- make bootstrap
script:
- cd $CODE_DIRECTORY # change dir into source
- make test 2>&1 # Run tests
