# Gopkg.toml

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.17"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "1.0.1"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[prune]
  go-tests = true
  unused-packages = true
